manager/urls.py
from django.urls import path

from manager.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TagCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagUpdateView,
    TagDeleteView,
    toggle_status
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path(
        "tasks/<int:pk>/toggle-status/",
        toggle_status,
        name="toggle-status",
    ),
]

app_name = "manager"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager")),
]

manager/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "-creation_date"]

    def __str__(self):
        return self.content

manager/forms.py
from django import forms

from manager.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = ["content", "deadline", "is_done", "tags"]


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]

manager/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from manager.forms import TaskForm
from manager.models import Task, Tag


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("manager:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("manager:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("manager:tag-list")


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "manager/task_list.html"
    paginate_by = 10
    queryset = Task.objects.all()


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("manager:task-list")


def toggle_status(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = not task.is_done
    task.save()
    return redirect("manager:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
{#    <link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
 <ul class="sidebar-nav list-group">
{#  {% if user.is_authenticated %}#}
{#    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>#}
{#    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>#}
{#  {% else %}#}
{#    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>#}
{#  {% endif %}#}

  <br>

  <li class="list-group-item"><a href="{% url 'manager:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'manager:tag-list' %}">Tags</a></li>
</ul>

templates/manager/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="{% url "manager:tag-list" %}">No</a>
  </form>

{% endblock %}

templates/manager/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/manager/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tag List
    <a href="{% url 'manager:tag-create' %}" class="btn btn-primary">
      Create
    </a>
  </h1>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.id }}
          </td>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'manager:tag-update' pk=tag.id %}">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'manager:tag-delete' pk=tag.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags in the list.</p>
  {% endif %}
{% endblock %}

templates/manager/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="{% url "manager:task-list" %}">No</a>
  </form>

{% endblock %}

templates/manager/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/manager/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 style="padding-left: 10px">
    TODO list
    <a style="float: right; margin-top: 15px; margin-right: 150px;" href="{% url 'manager:task-create' %}" class="btn btn-primary">
      Create task
    </a>
  </h1>
  {% if task_list %}
    <ul style="list-style-type: none; padding-left: 0">
        <hr>
      {% for task in task_list %}

        <li style="display: flex">
        <div style="margin-bottom: 40px;" class="col-sm-10">
          <h3><strong>{{ task.content }}</strong></h3>
            {% if task.is_done == False %}
              <strong style="color: red">Not done</strong>
            {% else %}
              <strong style="color: green">Done</strong>
            {% endif %}
          <br>
          Created: {{ task.creation_date }} {% if task.deadline %}<p style="color: brown">Deadline: {{ task.deadline }}</p>{% endif %}
          <br>
        <p style="color: darkgray">Tags:
        {% for tag in task.tags.all %}
          {{ tag.name }}
        {% endfor %}
        <a href="{% url 'manager:task-update' pk=task.pk %}">Update</a>
        <a href="{% url 'manager:task-delete' pk=task.pk %}">Delete</a></p>
        </div>
        <div class="col-sm-2">
          <form action="{% url 'manager:toggle-status' pk=task.pk %}" method="post" style="display: inline;">
            {% csrf_token %}
            {% if task.status %}
            <button type="submit" class="btn btn-secondary">
              Undo
            </button>
            {% else %}
            <button type="submit" class="btn btn-success">
              {% if task.is_done == False %}
              <strong>Complete</strong>
            {% else %}
              <strong>Undo</strong>
            {% endif %}
            </button>
            {% endif %}
          </form>
        </div>
        <hr>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks in list</p>
  {% endif %}
{% endblock %}